sudo: false
language: ruby
cache: bundler
rvm:
- 2.7.4

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "yu00mi97@gmail.com"
  - git config --global user.name "0andme"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "RuQdn2cMSMmIcLIUYW55twb9KGkWqAZ6wGdS2ys1oyWPgWelaumoMj2vnqq5xrb5aAiXQePxaEspozQht8Z5nbSwwRhRNEQB6bg27150qBHTEJBHtsQwfEVlcSZSRUm0aW6k5fn3cpARh3dnjKRlgHnPVYHeNjGh70NEbrK23ZPSA749FwvPjqeXsw2PicOKAoDKyowwMNs44avDoRcRtMOZpzMR4MbN6SymwekOtWqX/ILmqB74K6sqjU3J7/srf/a0ynYisoBf+sMLf+VaS8tWa8gE8nDZpT6bwRAJ/b8fxP13xGzQnXFsvgqGXi6kgOZ2xhj6JKfyJJz302Zcw3BS0NglpyY/rYmiuETJsGVHSKlBtUORJWSdOqQPR4En7oXZklc45h46jGqbxaVM5OmOc/cfcIsjtcXFASo2JRW3YJgyGeoRVy+LRyvtYF2K9JBWDq80aiLbuBNWzdeDZz1UIu65vaiT1NcEOOHUR3pF+l2e5DsAlkN+ENjvnz4N7L43vpEpoVeZr8vaTj7E1HXqxz6uiVBizvE6E2WXcOWXz02Oc2DVIMqHtWni5Qkrsne4W/mRBXY0EbGgDH/B3UkEFxJN1O7g/oGhors2jCQmKV6M+R1wNwAvIGHVJ4j1bd+3woftHNDrr7vr03HhX9C5TioHRUwzY3mA5O4nmmY="
branches:
  only:
    - main